pod 'WTAZoomNavigationController', '~> 1.0.7'
#pod 'PBJVideoPlayer', '~> 0.2.4'
pod 'TSMiniWebBrowser', '~> 1.0.1'
#pod 'FFmpegWrapper', '~> 1.0'
#pod 'PLPlayerKit', '~> 2.0.0'
pod 'KRVideoPlayer', '~> 1.0.1'
pod 'UIView+TKGeometry', '~> 0.2'
pod 'StandardPaths', '~> 1.6.4'
#pod 'kxmovie', '0.0.1'
#pod 'ALMoviePlayerController', '~>0.3.0' 
pod "AFNetworking", "~> 2.0"
pod 'JSONKit-NoWarning', '~> 1.2'
pod 'YTKKeyValueStore', '~> 0.1.2'
pod "TSMessages"
pod 'SVPullToRefreshImprove', '~> 0.5'
pod 'GCNetworkReachability', '~> 1.3.2'
